import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  img = "/img/art1.png"
  title = 'Guaranteeing Performance';
  article1 = "Performance is a critical attribute in evaluating the quality and dependability of service-oriented systems dependent on fault-tolerant architectures. Fault-tolerant architectures have been implemented with redundant techniques to ensure fault-tolerant services. However, replica-related overhead burdens fault-tolerant techniques with associated performance degradation in service delivery, and this consequentially discourages service consumers with discredits for service providers. In this paper, a fault-tolerant approach that adopts replication and diversity was employed on agent-oriented coordination toward guaranteeing the performance of the proposed fault-tolerant architecture solution under a large-scale service request load. In addition, the resultant architecture solution was simulated with Apache JMeter for performance evaluation considering the performability in the absence and presence of a fault load. The simulation experiments and results revealed the architecture's efficiency in fault tolerance via the timely coordination of logical and replica-related activities by software agents. Noteworthily, the continued service availability and performance were guaranteed for the architecture solution with a significant rate of regularity in the absence and presence of a replica-related fault. Therefore, this study's performance evaluation methods and results could serve as a veritable milestone for building fault-tolerant service systems with appreciable performability and contribute to the service-oriented fields where performance is inevitable. [ABSTRACT FROM AUTHOR] "
  title2 = "Hidden Malware Ratchets Up Cybersecurity"
  article2 = "The article discusses the cybersecurity risks that are associated with malware that is not detectable by traditional commercial anti-malware security software programs, and it mentions how cybercriminals have been known to hide malware infections in audio and video files, Internet of Things, and deep learning models. Malware-related issues involving machine learning models and deep neural networks are assessed, as well as artificial intelligence."
  title3 = "Process & Software Selection for Robotic Process Automation"
  article3 = "Robotic process automation (RPA) is a technology for office automation to imitate human behaviour when interacting with computers to perform digitized tasks manually, such as opening and closing applications, reading documents, entering data, and sending e-mails. As with any new digital technology answering the question of where to start and what is the right software, is challenging. In the case of RPA, the question of where to start depends on the selection of the business process to be automated and optimized. There are approaches for process selection in research, but they are relatively complex and have not been validated in practice. To fill this gap, we have simplified the process selection method and validated it on a practical example. We also present a simple method to select the appropriate RPA software. The criteria selection and evaluation were done with the Pairwise Comparison and Benefit Value Analysis method. This approach is relatively easy to follow and to apply in practice and thus also closes a gap in applied research. [ABSTRACT FROM AUTHOR] "
}
